TESTSUITES = ./.__testsuite.sv
UNITTESTS = ./uvm_object_unit_test.sv ./uvm_misc_unit_test.sv ./uvm_scope_stack_unit_test.sv ./uvm_printer_knobs_unit_test.sv ./uvm_component_unit_test.sv ./uvm_printer_unit_test.sv ./uvm_status_container_unit_test.sv

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
