INCDIR += /home/njohnson/sandbox/uvm-utest/src/base /home/njohnson/sandbox/uvm-utest/src/base

TESTSUITES = /home/njohnson/sandbox/uvm-utest/src/base/._home_njohnson_sandbox_uvm_utest_src_base_testsuite.sv
UNITTESTS = /home/njohnson/sandbox/uvm-utest/src/base/uvm_object_unit_test.sv /home/njohnson/sandbox/uvm-utest/src/base/uvm_misc_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk
