INCDIR += /home/jmtremblay/svunit/uvm-utest/src/base /home/jmtremblay/svunit/uvm-utest/src/base /home/jmtremblay/svunit/uvm-utest/src/base /home/jmtremblay/svunit/uvm-utest/src/base /home/jmtremblay/svunit/uvm-utest/src/base

TESTSUITES = /home/jmtremblay/svunit/uvm-utest/src/base/._home_jmtremblay_svunit_uvm_utest_src_base_testsuite.sv
UNITTESTS = /home/jmtremblay/svunit/uvm-utest/src/base/uvm_misc_unit_test.sv /home/jmtremblay/svunit/uvm-utest/src/base/uvm_object_unit_test.sv /home/jmtremblay/svunit/uvm-utest/src/base/uvm_printer_knobs_unit_test.sv /home/jmtremblay/svunit/uvm-utest/src/base/uvm_printer_unit_test.sv /home/jmtremblay/svunit/uvm-utest/src/base/uvm_scope_stack_unit_test.sv 

-include svunit.mk
include $(SVUNIT_INSTALL)/bin/cfg.mk

CLEANFILES += .uvm_object.print
